# Site settings
title: Privacy
tag_text: Privacy
description: A responsive single-page website
url: "https://jcabeza.github.io/privacy"
baseurl: "/"

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
